name: auto-merge

on:
  pull_request:

jobs:
  run:
    name: "auto-merging flag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "enable auto-merge on pull-request"
        run: gh pr merge --auto --rebase "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.PERSONAL_TOKEN}}
