name: test

on:
  push:
    branches-ignore:
      - main

jobs:
  cicd-tools:
    runs-on: "ubuntu-latest"
    steps:
      - name: "setup CI/CD tools cache"
        id: cache-cicd-tools
        uses: actions/cache@v2
        with:
          path: cicd-tools
          key: ${{ runner.os }}-cicd-tools-v20220315143056
      - name: "download assert-version binary"
        if: steps.cache-cicd-tools.outputs.cache-hit != 'true'
        run: |
          mkdir -p cicd-tools
          curl -Lo cicd-tools/assert-version https://github.com/lonepeon/cicd/releases/download/v20220315143056/assert-version-linux-386
          chmod u+x cicd-tools/assert-version

  file-generation-tests:
    needs: cicd-tools
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup go version"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: "setup CI/CD tools cache"
        id: cache-cicd-tools
        uses: actions/cache@v2
        with:
          path: cicd-tools
          key: ${{ runner.os }}-cicd-tools-v20220315143056
      - name: "assert go version"
        run: cicd-tools/assert-version go
      - name: "assert all files are generated"
        run: make test-generate

  integration-tests:
    needs: cicd-tools
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup go version"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: "setup CI/CD tools cache"
        id: cache-cicd-tools
        uses: actions/cache@v2
        with:
          path: cicd-tools
          key: ${{ runner.os }}-cicd-tools-v20220315143056
      - name: "assert go version"
        run: cicd-tools/assert-version go
      - name: "run integration tests"
        run: make test-integration

  format-tests:
    needs: cicd-tools
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup go version"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: "setup CI/CD tools cache"
        id: cache-cicd-tools
        uses: actions/cache@v2
        with:
          path: cicd-tools
          key: ${{ runner.os }}-cicd-tools-v20220315143056
      - name: "assert go version"
        run: cicd-tools/assert-version go
      - name: "run code format"
        run: make test-format
      - name: "run code lint"
        run: make test-lint
      - name: "run code security"
        run: make test-security

  unit-tests:
    needs: cicd-tools
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup go version"
        uses: actions/setup-go@v2
        with:
          go-version: "1.17.7"
      - name: "setup CI/CD tools cache"
        id: cache-cicd-tools
        uses: actions/cache@v2
        with:
          path: cicd-tools
          key: ${{ runner.os }}-cicd-tools-v20220315143056
      - name: "assert go version"
        run: cicd-tools/assert-version go
      - name: "run unit tests"
        run: make test-unit

  acceptance-tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "run acceptance tests"
        run: make test-acceptance-deps test-acceptance
